# ============================================================
# DATASET CONFIG
# ============================================================
## Self Collected Data
# dataset_name: self_collected
# scene_id: 00880-Nfvxx8J5NCo
# dataset_path: dataset/HM3D_collect/
# dataset_conf_path: config/data_config/dataset/self_collected.yaml

## Replica Dataset
# dataset_name: replica
# scene_id: room_0
# dataset_path: dataset/Replica
# dataset_conf_path: config/data_config/dataset/replica.yaml
# dataset_gt_path: dataset/Replica-Dataset/Replica_original

## ScanNet Dataset
dataset_name: scannet
scene_id: collection0
dataset_path: /home/zach/datasets/iadc-collected251105
dataset_conf_path: config/data_config/dataset/scannet.yaml
dataset_gt_path: dataset/scannet200/val

## TUM RGBD Dataset
# dataset_name: tum_rgbd
# scene_id: rgbd_dataset_freiburg3_walking_static
# dataset_path: dataset/TUM_RGBD
# dataset_conf_path: config/data_config/dataset/tum_rgbd.yaml


# ============================================================
# OUTPUT CONFIG
# ============================================================
# output directory
output_path: ./output/iadc_test0


# ============================================================
# LOGGING CONFIG
# ============================================================
# logging config
logging_config: ./config/support_config/logging_config.yaml